ProjectManagerSystem/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include
from django.urls import path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("__debug__/", include("debug_toolbar.urls")),
    path("social-auth/", include("social_django.urls", namespace="social")),
    path("", include("users.urls", namespace="users")),
    path("", include("projects.urls", namespace="projects")),
]

if not settings.AWS_S3:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

projects/urls.py
from django.urls import path

from projects.views import CommentCreatView
from projects.views import CommentDeleteView
from projects.views import CommentUpdateView
from projects.views import ProjectCreateView
from projects.views import ProjectDeleteView
from projects.views import ProjectDetailTasksView
from projects.views import ProjectDetailView
from projects.views import ProjectListView
from projects.views import ProjectUpdateView
from projects.views import TaskCreateView
from projects.views import TaskDeleteView
from projects.views import TaskDetailView
from projects.views import TaskListView
from projects.views import TaskUpdateView
from users.views import WorkerListView
from users.views import toggle_assign_to_task

urlpatterns = [
    path("projects/create/",
         ProjectCreateView.as_view(),
         name="create-project"),
    path("projects/", ProjectListView.as_view(), name="project-list"),
    path(
        "projects/<int:project_id>/workers/",
        WorkerListView.as_view(),
        name="project-workers"
    ),
    path(
        "projects/<int:pk>/update/",
        ProjectUpdateView.as_view(),
        name="update-project"
    ),
    path(
        "projects/<int:pk>/delete/",
        ProjectDeleteView.as_view(),
        name="delete-project"
    ),
    path(
        "projects/<int:pk>/detail/",
        ProjectDetailView.as_view(),
        name="project-detail"
    ),
    path(
        "projects/<int:pk>/tasks-list/",
        ProjectDetailTasksView.as_view(),
        name="project-task-list"
    ),
    path(
        "projects/<int:project_id>/tasks/create/",
        TaskCreateView.as_view(),
        name="task-create"
    ),
    path(
        "projects/<int:project_id>/tasks/<int:pk>/update/",
        TaskUpdateView.as_view(),
        name="task-update"
    ),
    path(
        "projects/<int:project_id>/tasks/<int:pk>/delete/",
        TaskDeleteView.as_view(),
        name="task-delete"
    ),
    path(
        "projects/tasks/",
        TaskListView.as_view(),
        name="task-list"
    ),
    path(
        "projects/<int:project_id>/tasks/<int:pk>/toggle-assign/",
        toggle_assign_to_task,
        name="toggle-task-assign",
    ),
    path(
        "projects/<int:project_id>/tasks/<int:pk>/detail/",
        TaskDetailView.as_view(),
        name="task-detail",
    ),
    path(
        "projects/<int:project_id>/tasks/<int:pk>/comments/create/",
        CommentCreatView.as_view(),
        name="comment-create",
    ),
    path(
        "projects/<int:project_id>/tasks/<int:task_id>/comments/<int:pk>/update/",
        CommentUpdateView.as_view(),
        name="comment-update",
    ),
    path(
        "projects/<int:project_id>/tasks/<int:task_id>/comments/<int:pk>/delete/",
        CommentDeleteView.as_view(),
        name="comment-delete",
    ),
]

app_name = "projects"

users/urls.py
from django.urls import include
from django.urls import path

from users.views import (
    IndexView,
    AddWorkerView,
    RegisterView,
    WorkerDetailView,
    WorkerUpdateView,
    WorkerListView,
)

urlpatterns = [
    path("accounts/", include("django.contrib.auth.urls")),
    path("", IndexView.as_view(), name="index"),
    path("register/", RegisterView.as_view(), name="register-user"),
    path("addworker/", AddWorkerView.as_view(), name="add-worker"),
    path(
        "accounts/profile/<int:pk>/",
        WorkerDetailView.as_view(),
        name="worker-detail"
    ),
    path(
        "accounts/profile/<int:pk>/update/",
        WorkerUpdateView.as_view(),
        name="worker-update",
    ),
    path("workers/", WorkerListView.as_view(), name="worker-list"),
]

app_name = "users"

projects/models.py
from django.conf import settings
from django.db import models

from users.models import WorkerUser


class Comment(models.Model):
    text = models.TextField(max_length=255)
    created = models.DateTimeField(auto_now_add=True)
    author = models.ForeignKey(
        WorkerUser,
        on_delete=models.CASCADE,
        related_name="comments"
    )

    class Meta:
        ordering = ["-created"]
        verbose_name = "comment"
        verbose_name_plural = "comments"

    def __str__(self):
        return f"{self.text}\nAuthor: {self.author}\nCreated: {self.created}"


class TackStatus(models.TextChoices):
    CREATED = "Created", "Created"
    IN_PROGRESS = "In progress", "In progress"
    CHECKING = "Checking", "Checking"
    DONE = "Done", "Done"


class TaskType(models.TextChoices):
    INDEFINITE = "Indefinite", "Indefinite"
    BUG = "Bug", "Bug"
    NEW_FEATURE = "New feature", "New feature"
    BREAKING_CHANGE = "Breaking change", "Breaking change"
    REFACTORING = "Refactoring", "Refactoring"
    QA = "Q&A", "Q&A"


class TaskPriority(models.TextChoices):
    LOW = "Low", "Low"
    MEDIUM = "Medium", "Medium"
    HIGH = "High", "High"
    CRITICAL = "Critical", "Critical"


class Task(models.Model):
    name = models.CharField(max_length=150, unique=True)
    description = models.TextField(max_length=1024)
    deadline = models.DateField(null=True, blank=True)
    is_completed = models.BooleanField(default=False)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    author = models.ForeignKey(
        WorkerUser,
        on_delete=models.CASCADE,
        related_name="author_tasks"
    )
    status = models.CharField(
        max_length=64, choices=TackStatus.choices, default=TackStatus.CREATED
    )
    type = models.CharField(
        max_length=64, choices=TaskType.choices, default=TaskType.INDEFINITE
    )
    priority = models.CharField(
        max_length=64, choices=TaskPriority.choices, default=TaskPriority.LOW
    )
    responsible_workers = models.ManyToManyField(
        settings.AUTH_USER_MODEL, related_name="worker_tasks"
    )
    comments = models.ManyToManyField(Comment, related_name="tasks")

    class Meta:
        ordering = ["-created"]
        verbose_name = "task"
        verbose_name_plural = "tasks"

    def __str__(self):
        return f"{self.name}"


class ProjectStatus(models.TextChoices):
    DEVELOPING = "Developing", "Developing"
    TESTING = "Testing", "Testing"
    DEBUGGING = "Debugging", "Debugging"
    DEPLOYING = "Deploying", "Deploying"


class Project(models.Model):
    name = models.CharField(max_length=150, unique=True)
    description = models.TextField(max_length=1024)
    status = models.CharField(
        max_length=64,
        choices=ProjectStatus.choices,
        default=ProjectStatus.DEVELOPING
    )
    deadline = models.DateField(null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    project_lead = models.ForeignKey(
        WorkerUser,
        on_delete=models.CASCADE,
        related_name="lead_projects",
        null=True,
        blank=True
    )
    responsible_workers = models.ManyToManyField(
        settings.AUTH_USER_MODEL,
        related_name="workers_projects",
    )
    tasks = models.ManyToManyField(
        Task, related_name="project_tasks"
    )

    class Meta:
        ordering = ["-created_at"]
        verbose_name = "project"
        verbose_name_plural = "projects"

    def __str__(self):
        return f"{self.name} by {self.project_lead}"

projects/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.mixins import UserPassesTestMixin
from django.db import transaction
from django.db.models import Count
from django.db.models import F
from django.db.models import Q
from django.http import HttpResponseRedirect
from django.urls import reverse_lazy
from django.views.generic import CreateView
from django.views.generic import DeleteView
from django.views.generic import DetailView
from django.views.generic import ListView
from django.views.generic import UpdateView

from projects.forms import CommentCreatForm
from projects.forms import ProjectCreateForm
from projects.forms import ProjectUpdateForm
from projects.forms import TaskCreateForm
from projects.forms import TaskUpdateForm
from projects.models import Comment
from projects.models import Project
from projects.models import TackStatus
from projects.models import Task
from projects.project_mixins import TaskMixin


class ProjectCreateView(
    LoginRequiredMixin,
    UserPassesTestMixin,
    CreateView
):
    model = Project
    form_class = ProjectCreateForm
    template_name = "projects/project_form.html"

    def test_func(self) -> bool:
        return self.request.user.role == "Supervisor"

    @transaction.atomic
    def form_valid(self, form) -> HttpResponseRedirect:
        form.instance.project_lead = self.request.user
        result = super(ProjectCreateView, self).form_valid(form)
        form.instance.responsible_workers.add(self.request.user)
        return result

    def get_context_data(self, **kwargs) -> dict:
        context = super(ProjectCreateView, self).get_context_data(**kwargs)
        next_url = self.request.GET.get("next")
        if next_url:
            context["referer"] = next_url
        context["is_update"] = False
        return context

    def get_success_url(self) -> str:
        return reverse_lazy("users:index")


class ProjectListView(LoginRequiredMixin, ListView):
    model = Project
    template_name = "projects/project_list.html"
    context_object_name = "project_list"
    queryset = Project.objects.prefetch_related("responsible_workers", "tasks")
    paginate_by = 10

    @staticmethod
    def get_annotate_params() -> dict:
        return Project.objects.annotate(
            tasks_in_progress_count=Count(
                "tasks",
                filter=~Q(tasks__status=TackStatus.DONE),
                distinct=True
            ),
            tasks_done_count=Count(
                "tasks",
                filter=Q(tasks__status=TackStatus.DONE),
                distinct=True
            ),
            responsible_workers_count=Count(
                "responsible_workers", distinct=True
            ),
            project_lead_username=F("project_lead__username"),
            project_lead_first_name=F("project_lead__first_name"),
            project_lead_last_name=F("project_lead__last_name"),
        )

    def get_context_data(self, **kwargs) -> dict:
        context = super(ProjectListView, self).get_context_data(**kwargs)
        next_url = self.request.GET.get("next")
        if next_url:
            context["referer"] = next_url
        total_projects = Project.objects.count()
        context["total_workers"] = total_projects

        annotate_params = self.get_annotate_params()

        context["project_list"] = annotate_params

        return context


class ProjectUpdateView(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    model = Project
    form_class = ProjectUpdateForm
    template_name = "projects/project_form.html"

    def test_func(self) -> bool:
        return self.request.user.role == "Supervisor"

    def get_context_data(self, **kwargs) -> dict:
        context = super(ProjectUpdateView, self).get_context_data(**kwargs)
        next_url = self.request.GET.get("next")
        if next_url:
            context["referer"] = next_url
        context["is_update"] = True
        return context

    def get_success_url(self) -> str:
        next_url = self.request.GET.get("next")
        if next_url:
            return next_url
        return reverse_lazy("projects:project-list")


class ProjectDeleteView(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    model = Project
    success_url = reverse_lazy("projects:project-list")
    template_name = "projects/project_delete_confirm.html"

    def test_func(self) -> bool:
        return self.request.user.role == "Supervisor"

    def get_context_data(self, **kwargs) -> dict:
        context = super(ProjectDeleteView, self).get_context_data(**kwargs)
        next_url = self.request.GET.get("next")
        if next_url:
            context["referer"] = next_url
        return context


class ProjectDetailView(LoginRequiredMixin, DetailView):
    model = Project
    template_name = "projects/project_detail.html"
    queryset = Project.objects.select_related("project_lead").prefetch_related(
        "responsible_workers", "tasks"
    )

    def get_context_data(self, **kwargs) -> dict:
        context = super(ProjectDetailView, self).get_context_data(**kwargs)
        next_url = self.request.GET.get("next")
        if next_url:
            context["referer"] = next_url
        return context


class ProjectDetailTasksView(LoginRequiredMixin, DetailView):
    model = Project
    template_name = "projects/project_task_list.html"
    queryset = Project.objects.prefetch_related(
        "responsible_workers",
        "tasks",
        "tasks__responsible_workers",
    )

    def get_context_data(self, **kwargs) -> dict:
        context = super(ProjectDetailTasksView, self).get_context_data(
            **kwargs
        )
        next_url = self.request.GET.get("next")
        if next_url:
            context["referer"] = next_url
        return context


class TaskListView(LoginRequiredMixin, ListView):
    model = Task
    template_name = "projects/task_list.html"
    context_object_name = "task_list"

    queryset = Task.objects.prefetch_related(
        "project_tasks",
        "responsible_workers",
        "project_tasks__responsible_workers"
    )

    def get_context_data(self, **kwargs) -> dict:
        context = super(TaskListView, self).get_context_data(**kwargs)
        next_url = self.request.GET.get("next")
        if next_url:
            context["referer"] = next_url

        return context


class TaskCreateView(
    LoginRequiredMixin,
    TaskMixin,
    UserPassesTestMixin,
    CreateView
):
    model = Task
    form_class = TaskCreateForm
    template_name = "projects/task_form.html"

    def test_func(self) -> bool:
        return (
                self.request.user.role == "Supervisor" or
                self.check_responsible_worker()
        )

    @transaction.atomic
    def form_valid(self, form) -> HttpResponseRedirect:
        form.instance.author = self.request.user
        result = super(TaskCreateView, self).form_valid(form)
        form.instance.responsible_workers.add(self.request.user)

        project = self.get_project()
        project.tasks.add(form.instance)
        project.save(update_fields=["updated"])
        return result

    def get_form_kwargs(self) -> dict[str, dict]:
        kwargs = super(TaskCreateView, self).get_form_kwargs()
        kwargs["project"] = self.get_project()
        return kwargs

    def get_context_data(self, **kwargs) -> dict:
        context = super(TaskCreateView, self).get_context_data(**kwargs)
        next_url = self.request.GET.get("next")
        if next_url:
            context["referer"] = next_url
        project = self.get_project()
        context["project"] = project
        return context

    def get_success_url(self) -> str:
        next_url = self.request.GET.get("next")
        if next_url:
            return next_url
        return reverse_lazy(
            "projects:task-list", args=[self.kwargs.get("project_id")]
        )


class TaskUpdateView(
    LoginRequiredMixin,
    TaskMixin,
    UserPassesTestMixin,
    UpdateView
):
    model = Task
    form_class = TaskUpdateForm
    template_name = "projects/task_form.html"

    def test_func(self) -> bool:
        return (
                self.request.user.role == "Supervisor" or
                self.check_responsible_worker()
        )

    def get_form_kwargs(self) -> dict[str, dict]:
        kwargs = super(TaskUpdateView, self).get_form_kwargs()
        kwargs["user_role"] = self.request.user.role
        kwargs["project"] = self.get_project()
        return kwargs

    def get_context_data(self, **kwargs) -> dict:
        context = super(TaskUpdateView, self).get_context_data(**kwargs)
        next_url = self.request.GET.get("next")
        if next_url:
            context["referer"] = next_url
        project = self.get_project()
        context["project"] = project
        context["is_update"] = True
        return context

    def get_success_url(self) -> str:
        next_url = self.request.GET.get("next")
        if next_url:
            return next_url
        return reverse_lazy(
            "projects:task-list", args=[self.kwargs.get("project_id")]
        )


class TaskDeleteView(
    LoginRequiredMixin,
    TaskMixin,
    UserPassesTestMixin,
    DeleteView
):
    model = Task
    template_name = "projects/task_confirm_delete.html"
    success_url = reverse_lazy("projects:task-list")

    def test_func(self):
        return (
                self.request.user.role == "Supervisor"
        )

    def get_context_data(self, **kwargs) -> dict:
        context = super(TaskDeleteView, self).get_context_data(**kwargs)
        next_url = self.request.GET.get("next")
        if next_url:
            context["referer"] = next_url
        return context

    def get_success_url(self) -> str:
        return reverse_lazy(
            "projects:project-task-list", args=[self.kwargs.get("project_id")]
        )


class TaskDetailView(
    LoginRequiredMixin,
    TaskMixin,
    DetailView
):
    model = Task

templates/projects/project_form.html
{% extends 'layouts/base.html' %}
{% load crispy_forms_filters %}

{% block title %}
  {% if is_update %}
    Update the project
  {% else %}
    Create a new project
  {% endif %}
{% endblock title %}

{% block content %}
  <div class="row justify-content-center">
    <div class="col-xl-6">
      <div class="card">
        <div class="card-body">
          <h2 class="text-muted mb-4"
              style="display: flex; justify-content: space-between; align-items: center;">
            <strong>
              {% if is_update %}
                Update the project
                {% if project.id %}
                  <a href="{% url 'projects:delete-project' pk=project.id %}"
                     class="btn btn-danger link-to-page">
                    Delete
                  </a>
                {% endif %}
              {% else %}
                Create a new project
              {% endif %}
            </strong>
          </h2>
          <form action="" method="post" novalidate
                enctype="multipart/form-data" novalidate>
            {% csrf_token %}
            {{ form|crispy }}
            <div>
              <input type="submit" value="Save" class="btn btn-primary">
              <a href="{{ referer }}" class="btn btn-danger">Cancel</a>
            </div>
          </form>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

templates/projects/project_task_list.html
{% extends 'layouts/base.html' %}

{% block title %}Project Detail{% endblock title %}

{% block content %}
  <div class="header pb-6 d-flex align-items-center"
       style="min-height: 150px; background-size: cover; background-position: center top;">
    <!-- Mask -->
    <span class="mask bg-gradient-default opacity-8"></span>
    <div class="container-fluid d-flex align-items-center">
      <div class="row" style="white-space: nowrap">
        <div class="col-lg-7 col-md-10">
          <h1 class="display-2 text-white">
            {{ project.name }}
          </h1>
        </div>
      </div>
    </div>
  </div>
  <!-- Page content -->
  <div class="container-fluid mt--6">
    <div class="row justify-content-center">
      <div class="col-xl-10 order-xl-5">
        <div class="card mx-auto">
          <div class="card-body">
            <div class="pl-lg-4">
              <div class="order-xl-5">
                <div class="row">
                  <div class="col-lg-6">
                    <div class="form-group">
                      <ul class="nav nav-pills nav-fill">
                        <li class="nav-item">
                          <a class="nav-link"
                             href="{% url 'projects:project-detail' object.id %}">
                            Overview
                          </a>
                        </li>
                        <li class="nav-item active" aria-current="page">
                          <a class="nav-link active"
                             href="{% url 'projects:project-task-list' object.id %}">
                            Tasks
                          </a>
                        </li>
                      </ul>
                    </div>
                  </div>
                  <div class="col-lg-6">
                    <div class="d-flex justify-content-end align-items-center">
                      <a href="{% url 'projects:task-create' object.id %}?next={{ request.path }}"
                         class="btn btn-primary">
                        Add new a task
                      </a>
                    </div>
                  </div>
                </div>
                <hr class="my-2"/>
                {% if object.tasks %}
                  <table class="table table-bordered border-primary">
                    <thead class="table-primary">
                    <tr class="text-center">
                      <th class="col-3">Created</th>
                      <th class="col-3">In progress</th>
                      <th class="col-3">Checking</th>
                      <th class="col-3">Done</th>
                    </tr>
                    </thead>
                    <tbody>
                    <tr>
                      <td>
                        {% for task in object.tasks.all %}
                          {% if task.status == "Created" %}
                            {% include "includes/task_card.html" %}
                            <br>
                          {% endif %}
                        {% endfor %}
                      </td>
                      <td>
                        {% for task in object.tasks.all %}
                          {% if task.status == "In progress" %}
                            {% include "includes/task_card.html" %}
                            <br>
                          {% endif %}
                        {% endfor %}
                      </td>
                      <td>
                        {% for task in object.tasks.all %}
                          {% if task.status == "Checking" %}
                            {% include "includes/task_card.html" %}
                            <br>
                          {% endif %}
                        {% endfor %}
                      </td>
                      <td>
                        {% for task in object.tasks.all %}
                          {% if task.status == "Done" %}
                            {% include "includes/task_card.html" %}
                            <br>
                          {% endif %}
                        {% endfor %}
                      </td>
                    </tr>
                    </tbody>
                  </table>
                {% else %}
                  There are no tasks yet.
                {% endif %}
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>

{% endblock content %}

<!-- Specific JS goes HERE -->
{% block javascripts %}{% endblock javascripts %}

templates/projects/task_detail.html
{% extends 'layouts/base.html' %}

{% block title %}Task Detail{% endblock title %}

{% block content %}
  <div class="header pb-6 d-flex align-items-center"
       style="min-height: 150px; background-size: cover; background-position: center top;">
    <!-- Mask -->
    <span class="mask bg-gradient-default opacity-8"></span>
    <!-- Header container -->
  </div>
  <!-- Page content -->
  <div class="container-fluid mt--7">
    <div class="row justify-content-center">
      <div class="col-xl-5 order-xl-1">
        <div class="card mx-auto">
          <div class="card-body">
            <div class="pl-lg-4">
              <div class="order-xl-5">
                <div class="row">
                  <div class="col-lg-6">
                    <div class="form-group">
                      <ul class="nav nav-pills nav-fill">
                        <li class="nav-item">
                          <a class="btn btn-outline-primary"
                             href="{% url 'projects:project-task-list' project.id %}">
                            Back
                          </a>
                        </li>
                        <li class="nav-item">
                          {% if request.user in responsible_workers %}
                            {% include "includes/assign_task.html" %}
                          {% endif %}
                        </li>
                      </ul>
                    </div>
                  </div>
                  <div class="col-lg-6">
                    <div class="d-flex justify-content-end align-items-center">
                      {% if request.user.role == "Supervisor" %}
                        <a href="{% url 'projects:task-update' project.id task.id %}?next={{ request.path }}"
                           class="btn btn-primary">
                          Edit task
                        </a>
                      {% endif %}
                    </div>
                  </div>
                </div>
                <hr class="my-2"/>
                <h6 class="heading-small text-muted mb-4">
                  Task detail
                </h6>
                <div class="pl-lg-1">
                  <div class="row">
                    <div class="col-lg-6">
                      <div class="form-group">
                        <label class="form-control-label">Task name</label>
                        <a class="form-control">{{ object.name }}</a>
                      </div>
                    </div>
                    <div class="col-lg-4">
                      <div class="form-group">
                        <label class="form-control-label">Status</label>
                        <a class="form-control">{{ object.status }}</a>
                      </div>
                    </div>
                  </div>
                  <div class="row">
                    <div class="col-lg-4">
                      <div class="form-group">
                        <label class="form-control-label">Last update</label>
                        <a class="form-control">{{ object.updated|date:"Y, F j H:i" }}</a>
                      </div>
                    </div>
                  </div>
                  <div class="row">
                    <div class="col-lg-6">
                      <div class="form-group">
                        <label class="form-control-label">Author</label>
                        <a class="form-control">{{ object.author }}</a>
                      </div>
                    </div>
                    <div class="col-lg-4">
                      <div class="form-group">
                        <label class="form-control-label">Deadline</label>
                        <a class="form-control">{{ object.deadline }}</a>
                      </div>
                    </div>
                  </div>
                  <div class="row">
                    <div class="col-lg-10">
                      <div class="form-group">
                        <label class="form-control-label">Description</label>
                        <textarea class="form-control" rows="6"
                                  disabled>{{ object.description }}
                </textarea>
                      </div>
                    </div>
                  </div>
                  <div class="row">
                    <div class="col-lg-10">
                      <div class="form-group">
                        <label class="form-control-label">
                          Responsible workers
                        </label>
                        {% if object.responsible_workers %}
                          {% for worker in object.responsible_workers.all %}
                            <a href="{% url 'users:worker-detail' pk=worker.id %}"
                               class="form-control mt-2">
                              {% if worker.first_name %}
                                {{ worker.first_name }}
                                {{ worker.first_name }}
                                ({{ worker.position }})
                              {% else %}
                                {{ worker.username }} (
                                {{ worker.position }})
                              {% endif %}
                            </a>
                          {% endfor %}
                        {% endif %}
                      </div>
                    </div>
                  </div>
                  <div class="row">
                    <div class="col-lg-10">
                      <div class="form-group">
                        <label class="form-control-label">
                          Comments
                        </label>
                        {% if request.user in responsible_workers %}
                          <a href="{% url 'projects:comment-create' project.id task.id %}?next={{ request.path }}%}"
                             class="btn btn-outline-success">
                            +
                          </a>
                        {% endif %}
                        <hr class="my-1"/>
                        {% if object.comments %}
                          {% for comment in object.comments.all %}
                            <p>{{ comment.text|linebreaksbr }}</p>
                            <strong>Author:</strong> {{ comment.author }}<br>
                            <strong>Created:</strong>
                            {{ comment.created|date:"Y, F j H:i" }}
                            {% if request.user.role == "Supervisor" %}
                              <div>
                                <a href="{% url 'projects:comment-update' project.id task.id comment.id %}?next={{ request.path }}">
                                  Edit
                                </a>
                                <a href="{% url 'projects:comment-delete' project.id task.id comment.id %}?next={{ request.path }}">
                                  Delete
                                </a>
                              </div>
                            {% endif %}
                            <hr class="my-1"/>
                          {% endfor %}
                        {% endif %}
                      </div>
                    </div>
                  </div>
                </div>
                <hr class="my-4"/>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>


{% endblock content %}

<!-- Specific JS goes HERE -->
{% block javascripts %}{% endblock javascripts %}