ProjectManagerSystem/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include
from django.urls import path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("__debug__/", include("debug_toolbar.urls")),
    path("social-auth/", include("social_django.urls", namespace="social")),
    path("", include("users.urls", namespace="users")),
    path("", include("projects.urls", namespace="projects")),
]

if not settings.AWS_S3:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

projects/urls.py
from django.urls import path

from projects.views import CommentCreatView
from projects.views import CommentDeleteView
from projects.views import CommentUpdateView
from projects.views import ProjectCreateView
from projects.views import ProjectDeleteView
from projects.views import ProjectDetailTasksView
from projects.views import ProjectDetailView
from projects.views import ProjectListView
from projects.views import ProjectUpdateView
from projects.views import TaskCreateView
from projects.views import TaskDeleteView
from projects.views import TaskDetailView
from projects.views import TaskListView
from projects.views import TaskUpdateView
from users.views import WorkerListView
from users.views import toggle_assign_to_task

urlpatterns = [
    path("projects/create/",
         ProjectCreateView.as_view(),
         name="create-project"),
    path("projects/", ProjectListView.as_view(), name="project-list"),
    path(
        "projects/<int:project_id>/workers/",
        WorkerListView.as_view(),
        name="project-workers"
    ),
    path(
        "projects/<int:pk>/update/",
        ProjectUpdateView.as_view(),
        name="update-project"
    ),
    path(
        "projects/<int:pk>/delete/",
        ProjectDeleteView.as_view(),
        name="delete-project"
    ),
    path(
        "projects/<int:pk>/detail/",
        ProjectDetailView.as_view(),
        name="project-detail"
    ),
    path(
        "projects/<int:pk>/tasks-list/",
        ProjectDetailTasksView.as_view(),
        name="project-task-list"
    ),
    path(
        "projects/<int:project_id>/tasks/create/",
        TaskCreateView.as_view(),
        name="task-create"
    ),
    path(
        "projects/<int:project_id>/tasks/<int:pk>/update/",
        TaskUpdateView.as_view(),
        name="task-update"
    ),
    path(
        "projects/<int:project_id>/tasks/<int:pk>/delete/",
        TaskDeleteView.as_view(),
        name="task-delete"
    ),
    path(
        "projects/tasks/",
        TaskListView.as_view(),
        name="task-list"
    ),
    path(
        "projects/<int:project_id>/tasks/<int:pk>/toggle-assign/",
        toggle_assign_to_task,
        name="toggle-task-assign",
    ),
    path(
        "projects/<int:project_id>/tasks/<int:pk>/detail/",
        TaskDetailView.as_view(),
        name="task-detail",
    ),
    path(
        "projects/<int:project_id>/tasks/<int:pk>/comments/create/",
        CommentCreatView.as_view(),
        name="comment-create",
    ),
    path(
        "projects/<int:project_id>/tasks/<int:task_id>/comments/<int:pk>/update/",
        CommentUpdateView.as_view(),
        name="comment-update",
    ),
    path(
        "projects/<int:project_id>/tasks/<int:task_id>/comments/<int:pk>/delete/",
        CommentDeleteView.as_view(),
        name="comment-delete",
    ),
]

app_name = "projects"

users/urls.py
from django.urls import include
from django.urls import path

from users.views import (
    IndexView,
    AddWorkerView,
    RegisterView,
    WorkerDetailView,
    WorkerUpdateView,
    WorkerListView,
)

urlpatterns = [
    path("accounts/", include("django.contrib.auth.urls")),
    path("", IndexView.as_view(), name="index"),
    path("register/", RegisterView.as_view(), name="register-user"),
    path("addworker/", AddWorkerView.as_view(), name="add-worker"),
    path(
        "accounts/profile/<int:pk>/",
        WorkerDetailView.as_view(),
        name="worker-detail"
    ),
    path(
        "accounts/profile/<int:pk>/update/",
        WorkerUpdateView.as_view(),
        name="worker-update",
    ),
    path("workers/", WorkerListView.as_view(), name="worker-list"),
]

app_name = "users"

templates/includes/assign_task.html
{% if request.user in task.responsible_workers.all %}
  <a href="{% url 'projects:toggle-task-assign' project_id=project.id pk=task.id %}?next={{ request.path }}"
     class="btn btn-danger btn-sm">
    Unassign
  </a>
{% else %}
  <a href="{% url 'projects:toggle-task-assign' project_id=project.id pk=task.id %}?next={{ request.path }}"
     class="btn btn-success btn-sm">
    Assign
  </a>
{% endif %}

templates/includes/footer-fullscreen.html
    <footer class="py-5">
      <div class="container">
        <div class="row align-items-center justify-content-xl-between">
          <div class="col-xl-6">
            <div class="copyright text-center text-xl-left text-muted">
                <a target="_blank" 
                   href="https://appseed.us/admin-dashboards/django" 
                   class="font-weight-bold ml-1" target="_blank">More Dashboards</a>
            </div>
          </div>
          <div class="col-xl-6">
            <div class="text-center text-xl-right text-muted">
               &copy; <a target="_blank" 
                         href="https://bit.ly/3fKQZaL">Creative-Tim</a> 
               - coded by <a target="_blank" href="https://appseed.us">AppSeed</a>
            </div>
          </div>
        </div>
      </div>
    </footer>

templates/includes/footer.html
      <!-- Footer -->
      <footer class="footer">
        <div class="row align-items-center justify-content-xl-between">
          <div class="col-xl-6">
            <div class="text-center text-xl-left text-muted">
              <a href="https://appseed.us/admin-dashboards/django" 
                 class="font-weight-bold ml-1" target="_blank">More Dashboards</a>
            </div>
          </div>
          <div class="col-xl-6">
            <div class="text-center text-xl-right text-muted">
              <a href="https://bit.ly/3fKQZaL" 
                 class="font-weight-bold ml-1" target="_blank"> &copy; Creative-Tim</a> 
                 - coded by <a target="_blank" href="https://appseed.us">AppSeed</a>
            </div>
          </div>
        </div>
      </footer>

templates/includes/navigation-fullscreen.html
<nav id="navbar-main"
     class="navbar navbar-horizontal navbar-transparent navbar-main navbar-expand-lg navbar-light">
  <div class="container">
    <a class="navbar-brand" href="/">
      <img src="/static/img/cad_icon.png"
           alt="CAD.Project System - Template Starter Logo.">
    </a>
    <button class="navbar-toggler" type="button" data-toggle="collapse"
            data-target="#navbar-collapse" aria-controls="navbar-collapse"
            aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="navbar-collapse navbar-custom-collapse collapse"
         id="navbar-collapse">
      <div class="navbar-collapse-header">
        <div class="row">
          <div class="col-6 collapse-brand">
            <a href="/">
              <img src="/static/img/cad_icon.png">
            </a>
          </div>
          <div class="col-6 collapse-close">
            <button type="button" class="navbar-toggler" data-toggle="collapse"
                    data-target="#navbar-collapse"
                    aria-controls="navbar-collapse" aria-expanded="false"
                    aria-label="Toggle navigation">
              <span></span>
              <span></span>
            </button>
          </div>
        </div>
      </div>
      <ul class="navbar-nav mr-auto">
        <li class="nav-item">
          {% if user.is_authenticated %}
            <form method="post" action="{% url 'users:logout' %}">
              {% csrf_token %}
              <button type="submit" class="btn btn-link nav-link">LogOut
              </button>
            </form>
          {% else %}
            <a href="{% url 'users:login' %}" class="nav-link">
              <span class="nav-link-inner--text">Login</span>
            </a>
          {% endif %}
        </li>
        <li class="nav-item">
          {% if not user.is_authenticated %}
          <a href="{% url 'users:register-user' %}" class="nav-link">
            <span class="nav-link-inner--text">Register</span>
          </a>
          {% endif %}
        </li>
      </ul>
      <hr class="d-lg-none"/>
      </ul>
    </div>
  </div>
</nav>

templates/includes/navigation.html
<nav
    class="navbar navbar-top navbar-expand navbar-dark bg-primary border-bottom">
  <div class="container-fluid">
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <div class="row align-items-center py-2">
        <div class="col-lg-auto col-7">
          <nav aria-label="breadcrumb"
               class="d-none d-md-inline-block ml-md-4">
          </nav>
        </div>
      </div>
      <!-- Navbar links -->
      <ul class="navbar-nav align-items-center  ml-md-auto ">
        <li class="nav-item d-xl-none">
          <!-- Sidenav toggler -->
          <div class="pr-3 sidenav-toggler sidenav-toggler-dark"
               data-action="sidenav-pin" data-target="#sidenav-main">
            <div class="sidenav-toggler-inner">
              <i class="sidenav-toggler-line"></i>
              <i class="sidenav-toggler-line"></i>
              <i class="sidenav-toggler-line"></i>
            </div>
          </div>
        </li>
        <li class="nav-item d-sm-none">
          <a class="nav-link" href="#" data-action="search-show"
             data-target="#navbar-search-main">
            <i class="ni ni-zoom-split-in"></i>
          </a>
        </li>
      </ul>
      <ul class="navbar-nav align-items-center  ml-auto ml-md-0 ">
        <li class="nav-item dropdown">
          <a class="nav-link pr-0" href="#" role="button"
             data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <div class="media align-items-center">
              <span class="avatar avatar-sm rounded-circle">
                {% if request.user.photo %}
                  <img alt="Image placeholder"
                       src="{{ request.user.photo.url }}"
                       class="rounded-circle">
                {% else %}
                  <img alt="Image placeholder"
                       src="/static/img/default-user-avatar.png">
                {% endif %}
              </span>
              <div class="media-body  ml-2  d-none d-lg-block">
                <span class="mb-0 text-sm  font-weight-bold">
                  {{ request.user.username }}
                </span>
              </div>
            </div>
          </a>
          <div class="dropdown-menu  dropdown-menu-right ">
            <div class="dropdown-header noti-title">
              <h6 class="text-overflow m-0">Welcome!</h6>
            </div>
            <a href="{% url 'users:worker-detail' pk=user.id %}"
               class="dropdown-item">
              <i class="ni ni-single-02"></i>
              <span>My profile</span>
            </a>
            <div class="dropdown-divider"></div>
            <form method="post" action="{% url 'users:logout' %}">
              {% csrf_token %}
              <div class="d-flex align-items-center">
                <i class="ni ni-user-run text-red ml-2"></i>
                <input class="dropdown-item" type="submit" value="Logout">
              </div>
            </form>
          </div>
        </li>
      </ul>
    </div>
  </div>
</nav>

templates/includes/pagination.html
{% if is_paginated %}
  <nav aria-label="Page navigation example">
    <ul class="pagination">
      {% if page_obj.has_previous %}
        <li class="page-item">
          <a href="?page={{ page_obj.previous_page_number }}" class="page-link" aria-label="Previous">
            <span aria-hidden="true">&laquo;</span>
          </a>
        </li>
      {% endif %}
      <li class="page-item active">
        <span class="page-link">{{ page_obj.number }}</span>
      </li>
      {% if page_obj.has_next %}
        <li class="page-item">
          <a href="?page={{ page_obj.next_page_number }}" class="page-link" aria-label="Next">
            <span aria-hidden="true">&raquo;</span>
          </a>
        </li>
      {% endif %}
    </ul>
  </nav>
{% endif %}

templates/includes/project_card.html
<div class="card mx-auto" style="width: 18rem;">
  <a href="{% url 'projects:project-detail' project.id %}">
    <div class="card-header">
      <strong>
        {{ project.name }}
      </strong>
      <br>
      <strong>Status:</strong> {{ project.status }}
    </div>
  </a>
  <div class="card-body">
    <h5 class="card-title">Describe</h5>
    <p class="card-text text-wrap">
      {{ project.description }}
    </p>
  </div>
  <ul class="list-group list-group-flush">
    <a href="{% url 'users:worker-detail' pk=project.project_lead_id %}">
      <li class="list-group-item">
        <b>Project lead:</b>
        {% if project.project_lead_first_name and project.project_lead_last_name %}
          {{ project.project_lead_first_name }}
          {{ project.project_lead_last_name }}
        {% else %}
          {{ project.project_lead_username }}

        {% endif %}
      </li>
    </a>
    <li class="list-group-item">
      <b>Created:</b>
      {{ project.created_at|date:"Y, F j" }}
      <br>
      <b>Deadline:</b>
      {{ project.deadline|date:"Y, F j" }}
      <br>
      <b>Last update:</b>
      {{ project.updated|date:"Y, F j H:i" }}
    </li>

    <li class="list-group-item">
      <a href="{% url 'projects:project-task-list' project.id %}">
        <b>Tasks in progress:</b>
        {{ project.tasks_in_progress_count }}
      </a>
      <br>
      <b>Completed tasks:</b>
      {{ project.tasks_done_count }}
    </li>
    <a href="{% url 'projects:project-workers' project.id %}">
      <li class="list-group-item">
        <b>Responsible workers:</b> {{ project.responsible_workers_count }}
      </li>
    </a>
  </ul>
  <div
      class="card-body d-flex justify-content-center">
    <a href="{% url 'projects:project-detail' project.id %}"
       class="btn btn-outline-primary">Detail</a>
    {% if request.user.role == "Supervisor" %}
      <a href="{% url 'projects:update-project' project.id %}?next={{ request.path }}"
         class="btn btn-outline-warning">Edite</a>
    {% endif %}
  </div>
</div>

templates/includes/project_card_profile.html
<div class="card mx-auto" style="width: 17rem;">
  <a href="{% url 'projects:project-detail' project.id %}">
    <div class="card-header">
      <strong>
        {{ project.name }}
      </strong>
      <br>
      <strong>Status:</strong> {{ project.status }}
    </div>
  </a>
  <div class="card-body">
    <h5 class="card-title">Describe</h5>
    <p class="card-text text-wrap">
      {{ project.description }}
    </p>
  </div>
  <ul class="list-group list-group-flush">
    <a href="{% url 'users:worker-detail' pk=project.project_lead_id %}">
      <li class="list-group-item">
        <b>Project lead:</b>
        {% if project.project_lead.first_name and project.project_lead.last_name %}
          {{ project.project_lead.first_name }}
          {{ project.project_lead.last_name }}
        {% else %}
          {{ project.project_lead.username }}

        {% endif %}
      </li>
    </a>
    <li class="list-group-item">
      <b>Deadline:</b>
      {{ project.deadline }}
    </li>
  </ul>
  <div
      class="card-body d-flex justify-content-center">
    <a href="{% url 'projects:project-detail' project.id %}"
       class="btn btn-outline-primary">Detail</a>
    {% if request.user.role == "Supervisor" %}
      <a href="{% url 'projects:update-project' project.id %}?next={{ request.path }}"
         class="btn btn-outline-warning">Edite</a>
    {% endif %}
  </div>
</div>

templates/includes/scripts.html
  <script src="/static/assets/vendor/jquery/dist/jquery.min.js"></script>
  <script src="/static/assets/vendor/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
  <script src="/static/assets/vendor/js-cookie/js.cookie.js"></script>
  <script src="/static/assets/vendor/jquery.scrollbar/jquery.scrollbar.min.js"></script>
  <script src="/static/assets/vendor/jquery-scroll-lock/dist/jquery-scrollLock.min.js"></script>

templates/includes/search.html
{% load bootstrap4 %}
{% load crispy_forms_filters %}

<form method="get" action="" class="navbar-search-light form-inline" role="search">
  {{ search_form|crispy }}
    <button type="button" 
            class="close" 
            data-action="search-close" 
            data-target="#navbar-search-main" 
            aria-label="Close">
  </button>
</form>

templates/includes/sidenav.html
<nav
    class="sidenav navbar navbar-vertical  fixed-left  navbar-expand-xs navbar-light bg-white"
    id="sidenav-main">
  <div class="scrollbar-inner">
    <!-- Brand -->
    <div class="navbar-inner">
      <!-- Collapse -->
      <div class="collapse navbar-collapse" id="sidenav-collapse-main">
        <!-- Nav items -->
        <ul class="navbar-nav">
          <li class="nav-item">
            <a class="nav-link {% if 'profile' in segment %} active {% endif %}"
               href="{% url 'users:worker-detail' pk=user.id %}">
              <i class="ni ni-single-02 text-yellow"></i>
              <span class="nav-link-text">My Profile</span>
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link {% if 'icons' in segment %} active {% endif %}"
               href="{% url 'users:worker-list' %}">
              <i class="ni ni-single-02 text-orange"></i>
              <span class="nav-link-text">My CoWorkers</span>
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link {% if 'map' in segment %} active {% endif %}"
               href="{% url 'projects:project-list' %}">
              <i class="ni ni-folder-17 text-primary"></i>
              <span class="nav-link-text">Projects</span>
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link {% if 'tables' in segment %} active {% endif %}"
               href="{% url 'projects:task-list' %}">
              <i class="ni ni-bullet-list-67 text-default"></i>
              <span class="nav-link-text">All Tasks</span>
            </a>
          </li>
        </ul>

        <hr class="my-3">
            <form method="post" action="{% url 'users:logout' %}">
              {% csrf_token %}
              <a class="nav-link">
                <div class="d-flex align-items-center">
                  <i class="ni ni-user-run text-red ml-2"></i>
                  <input class="dropdown-item" type="submit" value="Logout">
                </div>
              </a>
            </form>
      </div>
    </div>
  </div>
</nav>

templates/includes/task_card.html
<div class="card" style="width: 15rem;">
  <ul class="list-group list-group-flush">
    <a href="{% url 'projects:task-detail' project.id task.id %}?next={{ request.path }}">
      <li class="list-group-item">
        <strong>{{ task.name }}</strong>
        <br>
        {{ task.status }}
      </li>
    </a>
    <li class="list-group-item">
      <strong>Priority:</strong> {{ task.priority }}
      <br>
      <strong>Type:</strong> {{ task.type }}
      <br>
      <strong>Created:</strong> {{ task.created|date:"Y, F j" }}
      <br>
      <strong>Deadline:</strong> {{ task.deadline|date:"Y, F j" }}
      <br>
      <strong>Last update:</strong> {{ task.updated|date:"Y, F j H:i" }}
    </li>
    <li class="list-group-item">
      <a href="{% url 'projects:task-detail' project.id task.id %}?next={{ request.path }}"
         class="btn btn-outline-primary btn-sm">
        Detail
      </a>
      {% if request.user.role == "Supervisor" %}
        <a href="{% url 'projects:task-update' project.id task.id %}?next={{ request.path }}"
           class="btn btn-outline-warning btn-sm">
          Edite
        </a>
      {% endif %}
      {% if request.user in project.responsible_workers.all %}
        {% include "includes/assign_task.html" %}
      {% endif %}
    </li>
  </ul>
</div>