ProjectManagerSystem/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include
from django.urls import path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("__debug__/", include("debug_toolbar.urls")),
    path("social-auth/", include("social_django.urls", namespace="social")),
    path("", include("users.urls", namespace="users")),
    path("", include("projects.urls", namespace="projects")),
]

if not settings.AWS_S3:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

users/urls.py
from django.urls import include
from django.urls import path

from users.views import (
    IndexView,
    AddWorkerView,
    RegisterView,
    WorkerDetailView,
    WorkerUpdateView,
    WorkerListView,
)

urlpatterns = [
    path("accounts/", include("django.contrib.auth.urls")),
    path("", IndexView.as_view(), name="index"),
    path("register/", RegisterView.as_view(), name="register-user"),
    path("addworker/", AddWorkerView.as_view(), name="add-worker"),
    path(
        "accounts/profile/<int:pk>/",
        WorkerDetailView.as_view(),
        name="worker-detail"
    ),
    path(
        "accounts/profile/<int:pk>/update/",
        WorkerUpdateView.as_view(),
        name="worker-update",
    ),
    path("workers/", WorkerListView.as_view(), name="worker-list"),
]

app_name = "users"

users/models.py
from django.contrib.auth.models import AbstractUser
from django.core.exceptions import ValidationError
from django.db import models
from django.urls import reverse


class Position(models.TextChoices):
    GUEST = "Guest", "Guest"
    DEVELOPER = "Developer", "Developer"
    PROJECT_MANAGER = "Project Manager", "Project Manager"
    PRODUCT_MANAGER = "Product Manager", "Product Manager"
    QA = "QA", "QA"
    DESIGNER = "Designer", "Designer"
    DEVOPS = "DevOps", "DevOps"
    TEAM_LEAD = "Team Lead", "Team Lead"


class Role(models.TextChoices):
    GUEST = "Guest", "Guest"
    ENGINEER_MANAGER = "Engineer/Manager", "Engineer/Manager"
    SUPERVISOR = "Supervisor", "Supervisor"


class WorkerUser(AbstractUser):
    class Meta:
        ordering = ["username"]
        verbose_name = "worker"
        verbose_name_plural = "workers"

    role = models.CharField(
        max_length=64, choices=Role.choices, default=Role.GUEST
    )
    position = models.CharField(
        max_length=64, choices=Position.choices, default=Position.GUEST
    )
    phone_number = models.CharField(
        max_length=20,
        null=True,
        blank=True,
        unique=True,
        help_text="Phone number (+3XX XXX XXX XXX)"
    )
    telegram = models.CharField(
        max_length=20,
        null=True,
        blank=True,
        unique=True,
        help_text="Telegram username (@username)"
    )
    photo = models.ImageField(
        upload_to="media/users/photos/",
        null=True,
        blank=True,
        unique=False,
        help_text="Upload your photo",
    )

    is_active = models.BooleanField(
        default=True,
        help_text=(
            "Designates whether this user " "should be treated as active. "
        ),
    )

    is_supervisor = models.BooleanField(
        default=False,
        help_text="Defines or will have access to special "
                  "supervisor permissions"
    )

    last_activity = models.DateTimeField(null=True, blank=True)

    def clean(self):
        super().clean()
        if self.phone_number:
            if not self.phone_number.startswith("+3"):
                raise ValidationError("Phone number should start with '+3'.")
            if not self.phone_number[1:].isdigit():
                raise ValidationError(
                    "Phone number should contain only digits after '+3'."
                )
            if len(self.phone_number) < 5:
                raise ValidationError("Phone number is too short.")
            if len(self.phone_number) > 16:
                raise ValidationError("Phone number is too long.")

        if self.telegram:
            if not self.telegram.startswith("@"):
                raise ValidationError(
                    "Telegram username should start with '@'.")
            if len(self.telegram) < 2:
                raise ValidationError("Telegram username is too short.")

            self.telegram = self.telegram[1:]

        if self.photo:
            max_photo_size = 2097152
            if self.photo.size > max_photo_size:
                raise ValidationError(
                    f"Photo size is too large "
                    f"(max. {max_photo_size / 1024 / 1024}MB)"
                )

    def __str__(self):
        if self.first_name and self.last_name:
            return f"{self.first_name} {self.last_name} ({self.position})"
        return f"{self.username} ({self.position})"

    def get_absolute_url(self):
        return reverse("users:worker-detail", kwargs={"pk": self.pk})

users/forms.py
from django.contrib.auth.forms import UserCreationForm
from django import forms

from users.models import WorkerUser
from users.models import Role


class RegisterForm(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        model = WorkerUser
        fields = UserCreationForm.Meta.fields + (
            "email",
            "first_name",
            "last_name",
        )


class AddWorkerForm(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        model = WorkerUser
        fields = UserCreationForm.Meta.fields + (
            "role",
            "position",
            "is_active",
        )


class WorkerUserUpdateForm(forms.ModelForm):
    class Meta(UserCreationForm.Meta):
        model = WorkerUser

        fields = (
            "username",
            "email",
            "first_name",
            "last_name",
            "role",
            "position",
            "is_active",
            "phone_number",
            "telegram",
            # "photo",
        )

    def __init__(self, *args, **kwargs):
        user_role = kwargs.pop("user_role")
        super().__init__(*args, **kwargs)

        if user_role == Role.ENGINEER_MANAGER:
            self.fields.pop("position")
            self.fields.pop("role")
            self.fields.pop("is_active")


class WorkerSearchForm(forms.Form):
    title = forms.CharField(
        label="",
        max_length=150,
        required=False,
        widget=forms.TextInput(attrs={"placeholder": "Search CoWorkers"}),
    )

users/views.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.mixins import UserPassesTestMixin
from django.core.exceptions import PermissionDenied
from django.db.models import Count
from django.db.models import Prefetch
from django.db.models import Q
from django.db.models import QuerySet
from django.http import HttpRequest
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404
from django.shortcuts import redirect
from django.urls import reverse_lazy
from django.views.generic import CreateView
from django.views.generic import DetailView
from django.views.generic import ListView
from django.views.generic import TemplateView
from django.views.generic import UpdateView

from projects.models import Project, Task
from users.forms import AddWorkerForm
from users.forms import RegisterForm
from users.forms import WorkerSearchForm
from users.forms import WorkerUserUpdateForm
from users.models import WorkerUser


class IndexView(LoginRequiredMixin, TemplateView):
    def get(
            self,
            request: HttpRequest,
            *args,
            **kwargs
    ) -> HttpResponseRedirect:
        return redirect("projects:project-list")


class RegisterView(CreateView):
    model = WorkerUser
    form_class = RegisterForm
    template_name = "registration/register_form.html"

    success_url = reverse_lazy("users:login")


class AddWorkerView(
    LoginRequiredMixin,
    UserPassesTestMixin,
    CreateView
):
    model = WorkerUser
    form_class = AddWorkerForm
    success_url = reverse_lazy("users:worker-list")
    template_name = "users/worker_form.html"

    def test_func(self) -> bool:
        return self.request.user.role == "Supervisor"

    def get_context_data(self, **kwargs) -> dict:
        context = super(AddWorkerView, self).get_context_data(**kwargs)
        context["referer"] = self.request.META.get("HTTP_REFERER")
        context["is_update"] = False
        return context


class WorkerDetailView(LoginRequiredMixin, DetailView):
    model = WorkerUser
    template_name = "registration/profile.html"
    queryset = WorkerUser.objects.prefetch_related(
        Prefetch(
            "worker_tasks__project_tasks",
            queryset=Project.objects.all().prefetch_related(
                "responsible_workers",
            ).select_related("project_lead"),
        ),
        "worker_tasks__responsible_workers",
    )
    context_object_name = "worker"

    def get_context_data(self, **kwargs) -> dict:
        context = super(WorkerDetailView, self).get_context_data(**kwargs)
        user = self.object

        if user.id != self.request.user.id:
            context["display_position"] = user.position
            if user.first_name and user.last_name:
                context["display_name"] = f"{user.first_name} {user.last_name}"
            else:
                context["display_name"] = user.username
        else:
            context["display_position"] = self.request.user.position
            if self.request.user.first_name and self.request.user.last_name:
                context["display_name"] = (
                    f"{self.request.user.first_name} "
                    f"{self.request.user.last_name}"
                )
            else:
                context["display_name"] = self.request.user.username

        return context


class WorkerUpdateView(
    LoginRequiredMixin,
    UserPassesTestMixin,
    UpdateView
):
    model = WorkerUser
    form_class = WorkerUserUpdateForm
    template_name = "users/worker_form.html"

    def test_func(self) -> bool:
        return (
                self.get_object().id == self.request.user.id
                or self.request.user.role == "Supervisor"
        )

    def get_form_kwargs(self) -> dict:
        kwargs = super().get_form_kwargs()
        kwargs["user_role"] = self.request.user.role

        return kwargs

    def get_context_data(self, **kwargs) -> dict:
        context = super(WorkerUpdateView, self).get_context_data(**kwargs)
        next_url = self.request.GET.get("next")
        if next_url:
            context["referer"] = next_url
        context["is_update"] = True
        return context

    def get_success_url(self) -> str:
        next_url = self.request.GET.get("next")
        if next_url:
            return next_url
        return reverse_lazy(
            "users:worker-detail", kwargs={"pk": self.object.id}
        )


class WorkerListView(LoginRequiredMixin, ListView):
    model = WorkerUser
    template_name = "users/worker_list.html"
    context_object_name = "worker_list"
    paginate_by = 10

    def get_context_data(self, *, object_list=None, **kwargs) -> dict:
        context = super(WorkerListView, self).get_context_data(**kwargs)
        context["total_workers"] = WorkerUser.objects.count()

        project_id = self.kwargs.get("project_id")
        if project_id:
            project = get_object_or_404(Project, id=project_id)
            context["project"] = project

        queryset = self.get_queryset()
        annotate_params = queryset.annotate(
            worker_project_count=Count("workers_projects"),
            lead_project_count=Count("lead_projects"),
        ).order_by("username")

        context["worker_list"] = annotate_params

        title = self.request.GET.get("title", "")
        context["search_form"] = WorkerSearchForm(initial={"title": title})

        return context

    def get_queryset(self) -> QuerySet:
        queryset = WorkerUser.objects.all()
        form = WorkerSearchForm(self.request.GET)
        project_id = self.kwargs.get("project_id")

        if project_id:
            project = get_object_or_404(Project, id=project_id)
            queryset = project.responsible_workers.all()
            return queryset

        if form.is_valid():
            search_term = form.cleaned_data["title"]
            search_conditions = (
                    Q(username__icontains=search_term)
                    | Q(first_name__icontains=search_term)
                    | Q(last_name__icontains=search_term)
            )
            return queryset.filter(search_conditions)

        return queryset


def get_project(request: HttpRequest, project_id: int) -> Project:
    project = get_object_or_404(Project, id=project_id)
    return project


def check_responsible_worker(request: HttpRequest, project_id: int) -> bool:
    project = get_project(request, project_id)
    return request.user in project.responsible_workers.all()


@login_required
def toggle_assign_to_task(
        request: HttpRequest,
        project_id: int,
        pk: int
) -> HttpResponseRedirect:
    if request.user.role != "Supervisor" or not check_responsible_worker(
            request, project_id
    ):
        raise PermissionDenied

    worker = request.user
    task = get_object_or_404(Task, id=pk)
    if worker in task.responsible_workers.all():
        task.responsible_workers.remove(worker)
    else:
        task.responsible_workers.add(worker)

    next_url = request.GET.get("next")
    if next_url:
        return HttpResponseRedirect(next_url)
    return HttpResponseRedirect(
        reverse_lazy("projects:project-task-list", args=[project_id]))

templates/users/worker_form.html
{% extends 'layouts/base.html' %}
{% load crispy_forms_filters %}

{% block title %}
  {% if is_update %}
    Update information
  {% else %}
    Add new worker
  {% endif %}
{% endblock title %}

{% block content %}

  <div class="header pb-6 d-flex align-items-center"
       style="min-height: 300px; background-size: cover; background-position: center top;">
    <!-- Mask -->
    <span class="mask bg-gradient-default opacity-8"></span>
    <!-- Header container -->
  </div>
  <!-- Page content -->
  <div class="container-fluid mt--9">
    <div class="row justify-content-center">
      <div class="col-xl-6">
        <div class="card">
          <div class="card-body">
            <h2 class="text-muted mb-4">
              <strong>
                {% if is_update %}
                  Update information
                {% else %}
                  Add new worker
                {% endif %}
              </strong>
            </h2>
            <form action="" method="post" novalidate
                  enctype="multipart/form-data" novalidate>
              {% csrf_token %}
              {{ form|crispy }}
              {% if object.id == request.user.id %}
                <div class="mb-5">
                  <a href="{% url 'users:password_change' %}"
                     class="btn btn-outline-primary">
                    Change password
                  </a>
                  <a href="{% url 'users:password_reset' %}"
                     class="btn btn-outline-danger">
                    Reset password
                  </a>
                </div>
              {% endif %}
              <div>
                <input type="submit" value="Save" class="btn btn-primary">
                <a href="{{ referer }}" class="btn btn-danger">Cancel</a>
              </div>
            </form>
          </div>
        </div>
      </div>
    </div>

    {#    {% include "includes/footer.html" %}#}

  </div>

{% endblock content %}

<!-- Specific JS goes HERE -->
{% block javascripts %}{% endblock javascripts %}

templates/users/worker_list.html
{% extends 'layouts/base.html' %}

{% block title %}My CoWorkers{% endblock title %}

{% block content %}

  <div class="header pb-6 d-flex align-items-center"
       style="min-height: 300px; background-size: cover; background-position: center top;">
    <!-- Mask -->
    <span class="mask bg-gradient-default opacity-8"></span>
    <div class="container-fluid d-flex align-items-center">
      <div class="row" style="white-space: nowrap">
        <div class="col-lg-7 col-md-10">
          <h1 class="display-2 text-white">
            {% if project %}
              Responsible workers in {{ project.name }}
            {% else %}
              My CoWorkers
            {% endif %}
          </h1>
        </div>
      </div>
    </div>
  </div>
  <!-- Page content -->
  <div class="container-fluid mt--9">
  <div class="row">
    <div class="col-xl-12 order-xl-1">
      <div class="card">
        <div class="card-body">
          <form>
            <div class="pl-lg-4">
              <div class="row">
                <div class="container-fluid">
                  <div class="row">
                    <div class="col-lg-4 col-md-4 d-flex align-items-center">
                      <div class="text-left">
                        <strong>Total workers:</strong>
                        {% if project %}
                          {{ project.responsible_workers.count }}
                        {% else %}
                          {{ total_workers }}
                        {% endif %}
                      </div>
                    </div>
                    <div
                        class="col-lg-4 col-md-4 d-flex justify-content-center align-items-center">
                      {% if not project %}
                        <div>
                          {% include 'includes/search.html' %}
                        </div>
                      {% endif %}
                    </div>
                    {% if not project %}
                      <div
                          class="col-lg-4 col-md-4 d-flex justify-content-end align-items-center">
                        {% if object.id == request.user.id or request.user.role == "Supervisor" %}
                          <a href="{% url 'users:add-worker' %}"
                             class="btn btn-success">
                            Add new Worker
                          </a>
                        {% endif %}
                      </div>
                    {% endif %}
                  </div>
                </div>
                {% if worker_list %}
                  <table class="table table-striped mt-4">
                    <tr class="text-center">
                      <th>ID</th>
                      <th>Username</th>
                      <th>First name</th>
                      <th>Last name</th>
                      <th>Position</th>
                      <th>Num of projects</th>
                      {% if request.user.role == "Supervisor" %}
                        <th>Role</th>
                        <th>Active account</th>
                        <th>Edite</th>
                      {% endif %}
                    </tr>
                    {% for worker in worker_list %}
                      <tr
                          {% if worker.id == request.user.id %}
                            class="text-center table-success"
                          {% endif %}
                          {% if not worker.is_active %}
                            class="text-center table-danger"
                          {% else %}
                            class="text-center"
                          {% endif %}>
                      <td>{{ worker.id }}</td>
                      <td>
                        <a class="link-primary"
                           href="{{ worker.get_absolute_url }}">
                          {{ worker.username }}
                        </a>
                      </td>
                      <td>{{ worker.first_name }}</td>
                      <td>{{ worker.last_name }}</td>
                      <td>{{ worker.position }}</td>
                      {% if worker.role == "Supervisor" %}
                        <td>{{ worker.lead_project_count }}</td>
                      {% else %}
                        <td>{{ worker.worker_project_count }}</td>
                      {% endif %}
                      {% if request.user.role == "Supervisor" %}
                        <td>{{ worker.role }}</td>
                        <td>
                          {% if worker.is_active %}
                            <span style="color: green;">&#10004;</span>
                          {% else %}
                            <span style="color: red;">&#10060;</span>
                          {% endif %}
                        </td>
                        <td><a
                            href="{% url 'users:worker-update' pk=worker.id %}?next={{ request.path }}"
                            class="btn btn-outline-success">Edit profile</a>
                        </td>
                      {% endif %}
                    {% endfor %}
                    </tr>
                  </table>
                {% else %}
                  <p>There are no coworkers in the service.</p>
                {% endif %}
              </div>
              <hr class="my-4"/>
              <div class="text-center mx-auto">
                {% include 'includes/pagination.html' %}
              </div>
            </div>
        </div>
      </div>
    </div>

    {#    {% include "includes/footer.html" %}#}

  </div>

{% endblock content %}

<!-- Specific JS goes HERE -->
{% block javascripts %}{% endblock javascripts %}